title: Darul Uloom Seattle
email: info@darululooomseattle.org
description:
author:
org:
  contact:
    email: info@darululooomseattle.org
    phone: +1-425-351-5668
    address: 16771 ne 80th Street, Suite 100, Redmod wa 98052


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

exclude:
  - LICENSE
  - README.md
  - fresh.gif
  - .idea/workspace.xml

# Social Profiles
twitter_username:
github_username:
facebook_username:
